name: Process Tariffs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run on the first day of each month

jobs:
  process-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Download Raw Data
      run: python scripts/download.py
    - name: Filter by Sector, Service Type
      run: python scripts/filter.py
    - name: Convert to Our Format
      run: python scripts/convert.py
    - name: Merge data from wwtp-energy-tariffs
      run: python scripts/merge.py
    - name: Validate Output
      run: python scripts/validate.py
    - name: Zip Files
      uses: papeloto/action-zip@v1
      with:
        files: data/validated/
        dest: data/industrial-electricity-tariffs.zip
    - name: set VERSION
      run: echo "VERSION=$(date -I | sed 's/-/./g')" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: data/industrial-electricity-tariffs.zip
        asset_name: industrial-electricity-tariffs.zip
        asset_content_type: application/zip