name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-code-cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        python -m pytest --cov-report xml --cov=scripts tests/ -vv
        codecov -t ${{ secrets.CODECOV_TOKEN }}